export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE'
}

export const categoryConstants = {
    GET_ALL_CATEGORY_REQUEST: 'GET_ALL_CATEGORY_REQUEST',
    GET_ALL_CATEGORY_SUCCESS: 'GET_ALL_CATEGORY_SUCCESS',
    GET_ALL_CATEGORY_FAILURE: 'GET_ALL_CATEGORY_FAILURE',
    POST_ALL_CATEGORY_REQUEST: 'POST_ALL_CATEGORY_REQUEST',
    POST_ALL_CATEGORY_SUCCESS: 'POST_ALL_CATEGORY_SUCCESS',
    POST_ALL_CATEGORY_FAILURE: 'POST_ALL_CATEGORY_FAILURE',
    ADD_NEW_CATEGORY_REQUEST: 'ADD_NEW_CATEGORY_REQUEST',
    ADD_NEW_CATEGORY_SUCCESS: 'ADD_NEW_CATEGORY_SUCCESS',
    ADD_NEW_CATEGORY_FAILURE: 'ADD_NEW_CATEGORY_FAILURE'
}

export const productConstants = {
    POST_ALL_PRODUCTS_REQUEST: 'POST_ALL_PRODUCTS_REQUEST',
    POST_ALL_PRODUCTS_SUCCESS: 'POST_ALL_PRODUCTS_SUCCESS',
    POST_ALL_PRODUCTS_FAILURE: 'POST_ALL_PRODUCTS_FAILURE'
}

export const initialConstants = {
    INITIAL_DATA_REQUEST: 'INITIAL_DATA_REQUEST',
    INITIAL_DATA_SUCCESS: 'INITIAL_DATA_SUCCESS'
}